# Host specific configs
dns_name: frontend.acavinash.fun

# For example: specific backend version (optional)
frontend_version: v1

ansible_user: ec2-user
ansible_ssh_private_key_file: /home/ec2-user/contact-manager-roles/secret/terraform.pem