app_user: roboshop
app_dir: /app
node_version: "18"

# Monitoring

monitoring_dir: /opt/monitoring
prometheus_port: 9090
grafana_port: 3000

prometheus_config_path: "{{ monitoring_dir }}/prometheus.yml"
grafana_data_dir: "{{ monitoring_dir }}/grafana/data"
grafana_config_dir: "{{ monitoring_dir }}/grafana/conf"

prometheus_version: "2.48.0"
prometheus_download_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

grafana_version: "10.0.2"
grafana_download_url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"


