- name: Create monitoring directory
  file:
    path: "{{ monitoring_dir }}"
    state: directory
    owner: "{{ app_user }}"
    mode: 0755

- name: Download Prometheus
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus.tar.gz"

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "{{ monitoring_dir }}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Copy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_path }}"
  notify: Restart Prometheus

- name: Create Prometheus service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
