- name: Remove older Node.js versions
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Add NodeSource repo for Node.js {{ node_version }}
  ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }}.x | bash -

- name: Install Node.js
  package:
    name: nodejs
    state: present
